DYNAMIC_FLAVOR_BASES = {
    "alkaline-bath": [
        "Poppy Seed Crusted",
        "Toasted Onion & Chive",
        "Sweet Molasses",
        "Black Pepper Asiago",
        "Sundried Tomato Basil",
        "Smoked Paprika Glazed",
        "Sourdough Rye Twist",
        "Maple Brown Sugar",
        "Cheddar Herb Butter",
        "Spiced Pumpkin Seed",
        "Garlic Herb Infusion",
        "Sweet Honey Oat",
    ],
    "cakes-batters": [
        "Lemon Raspberry Drizzle",
        "Spiced Apple Streusel",
        "Rich Fudge Marble",
        "Banana Chocolate Chunk",
        "Toasted Almond Peach",
        "Orange Cranberry Spice",
        "Classic Red Velvet",
        "Vanilla Cream Swirl",
        "Coconut Pineapple Delight",
        "Gingerbread Molasses",
        "Maple Pecan Muffin",
        "Strawberry Buttermilk",
    ],
    "choux-paste": [
        "Pecan Maple Cream",
        "White Chocolate Raspberry",
        "Dark Chocolate Orange",
        "Salted Caramel Pecan",
        "Vanilla Custard Glaze",
        "Double Chocolate Mousse",
        "Coffee Espresso Swirl",
        "Lemon Meringue Puff",
        "Spiced Apple Cinnamon",
        "Toasted Almond Praline",
        "Blueberry Cream Custard",
        "Sweet Coconut Cream",
    ],
    "cookies-shortbread": [
        "Snickerdoodle Cinnamon",
        "Triple Chocolate Chunk",
        "White Chocolate Macadamia",
        "Chewy Oatmeal Raisin",
        "Lemon Zest Butter",
        "Spiced Ginger Molasses",
        "Classic Sugar Sparkle",
        "Toasted Pecan Shortbread",
        "Double Fudge Brownie Drop",
        "Maple Walnut Cookie",
        "Cranberry Orange Drop",
        "Almond Butter Sandies",
    ],
    "enriched-soft": [
        "Chocolate Fudge Babka",
        "Cinnamon Streusel Swirl",
        "Sweet Maple Braid",
        "Orange Blossom Honey Rolls",
        "Cardamom Almond Crown",
        "Buttermilk Parker House",
        "Spiced Pumpkin Brioche",
        "Vanilla Custard Roll",
        "Toasted Coconut Buns",
        "Raspberry Jam Twists",
        "Apple Cinnamon Morning Buns",
        "Golden Egg Dinner Rolls",
    ],
    "flatbreads-griddles": [
        "Everything Bagel Focaccia",
        "Garlic Butter Naan",
        "Spinach Feta Piadina",
        "Pesto Mozzarella Flatbread",
        "Caramelized Onion Roti",
        "Toasted Sesame Pita",
        "Chili Flake Olive Flatbread",
        "Rosemary Parmesan Focaccia",
        "Sweet Honey Butter Crumpet",
        "Roasted Garlic Herb Pita",
        "Smoked Paprika Flatbread",
        "Za'atar Olive Flatbread",
    ],
    "fresh-pasta-noodles": [
        "Saffron Egg Tagliatelle",
        "Spinach Ricotta Ravioli",
        "Beet Root Pink Lasagna",
        "Squid Ink Black Linguine",
        "Porcini Mushroom Fettuccine",
        "Roasted Garlic Pappardelle",
        "Black Pepper Semolina Pasta",
        "Basil Pesto Penne",
        "Tomato Paste Fettuccine",
        "Lemon Herb Tagliolini",
        "Spiced Red Pepper Pappardelle",
        "Whole Grain Durum Noodle",
    ],
    "fried-doughs": [
        "Apple Cider Fritter",
        "Maple Glazed Bacon Donut",
        "Meyer Lemon Curd Berliner",
        "Chocolate Frosted Glaze",
        "Cinnamon Sugar Beignet",
        "Cardamom Spiced Churro",
        "Raspberry Jam Jelly Donut",
        "Powdered Sugar Funnel Cake",
        "Vanilla Bean Glazed Cruller",
        "Spiced Pumpkin Donut",
        "Toasted Coconut Fry Bread",
        "Blueberry Glazed Donut",
    ],
    "lean-crusty": [
        "Fig & Walnut Sourdough",
        "Cranberry Pecan Batard",
        "Toasted Sesame Boule",
        "Olive Oregano Sourdough",
        "Roasted Garlic Hearth Batard",
        "Rosemary French Baguette",
        "Multigrain Honey Seeded Boule",
        "Dark Beer Stout Rye",
        "Classic Country Sourdough",
        "Sun-Dried Tomato Batard",
        "Spiced Pumpkin Seed Hearth",
        "Ancient Grain Emmer Boule",
    ],
    "pastry-lamination": [
        "Meyer Lemon Cream Danish",
        "Almond Frangipane Turnover",
        "Raspberry Jam Pinwheel",
        "Cinnamon Sugar Palmier",
        "Vanilla Custard Fruit Plait",
        "Maple Butter Laminated Knot",
        "Chocolate Hazelnut Croissant",
        "Orange Glazed Cruffin",
        "Cardamom Spiced Morning Roll",
        "Toasted Pecan Laminated Twist",
        "Apple Compote Turnover",
        "Savory Ham Cheese Croissant",
    ],
    "quick-breads-scones": [
        "Zucchini Walnut Quick Bread",
        "Blueberry Lemon Glazed Scone",
        "Maple Pecan Oatmeal Scone",
        "Cranberry Orange Loaf",
        "Chocolate Chip Banana Bread",
        "Sharp Cheddar Herb Scone",
        "Spiced Pumpkin Ginger Bread",
        "Honey Butter Cornbread",
        "Vanilla Bean Blackberry Scone",
        "Apple Streusel Quick Loaf",
        "Savory Bacon Green Onion Scone",
        "Toasted Almond Poppyseed",
    ],
}

DYNAMIC_FLAVOR_DESCRIPTIONS = [
    "A beautiful, aromatic variant optimized to accentuate whole grain notes.",
    "A texture-focused twist featuring hydration adjustments for a softer bite.",
    "A premium profile featuring rich inclusion blending and deep flavor depth.",
    "An artisanal variation using custom preferment ratios for complex aromatics.",
    "A delightful variation balancing sweet/savory flavor tones and fine crumb.",
    "A rustic formula prioritizing crumb tenderness and high oven spring.",
    "A mouthwatering twist designed for uniform heat distribution and crispy edges.",
    "A sophisticated variation adding subtle spices to contrast the grain profile.",
    "A modern take with adjusted baking parameters to produce a stunning crust.",
    "A highly reliable recipe modification designed for consistent, delicious results.",
]
