# Generated by Django 6.0.4 on 2026-06-20 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoughCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('base_hydration', models.FloatField(help_text='Water ratio relative to flour (1.0 = 100%)')),
                ('base_fat', models.FloatField(default=0.0, help_text='Fat ratio relative to flour')),
                ('base_sugar', models.FloatField(default=0.0, help_text='Sugar ratio relative to flour')),
                ('base_salt', models.FloatField(default=0.02, help_text='Salt ratio relative to flour')),
                ('base_yeast', models.FloatField(default=0.015, help_text='Yeast ratio relative to flour (if chemically/yeast leavened)')),
                ('base_starter', models.FloatField(default=0.0, help_text='Starter ratio relative to flour (if sourdough)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Dough Categories',
                'indexes': [models.Index(fields=['slug'], name='core_doughc_slug_18071a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_portioned', models.BooleanField(default=False, help_text='True if baked in count-based units rather than a single loaf')),
                ('target_weight', models.FloatField(default=900.0, help_text='Target weight in grams for a single loaf')),
                ('unit_weight', models.FloatField(default=80.0, help_text='Weight in grams for one portioned item')),
                ('default_count', models.IntegerField(default=1, help_text='Default number of portioned items')),
                ('bake_temp_f', models.IntegerField(default=375, help_text='Baking temperature in Fahrenheit')),
                ('bake_time_min', models.IntegerField(default=35, help_text='Baking time in minutes')),
                ('steam_required', models.BooleanField(default=False, help_text='True if steam should be introduced in the oven')),
                ('is_enriched_profile', models.BooleanField(default=False, help_text='Determines if it uses enriched target probe temp (190F) vs lean (205F)')),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='core_formfa_slug_ddc24e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='core_system_key_f40380_idx')],
            },
        ),
        migrations.CreateModel(
            name='BreadPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('hydration_override', models.FloatField(blank=True, null=True)),
                ('fat_override', models.FloatField(blank=True, null=True)),
                ('sugar_override', models.FloatField(blank=True, null=True)),
                ('starter_override', models.FloatField(blank=True, null=True)),
                ('flour_type_default', models.CharField(default='all_purpose', max_length=50)),
                ('flour_maturity_default', models.CharField(default='matured', max_length=50)),
                ('dough_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='core.doughcategory')),
                ('form_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='core.formfactor')),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='core_breadp_slug_914f4d_idx')],
            },
        ),
    ]
