# Generated by Django 6.0.4 on 2026-06-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpreset',
            name='accessibility_definition',
            field=models.TextField(blank=True, help_text='Brief accessibility definition'),
        ),
        migrations.AddField(
            model_name='breadpreset',
            name='classifier_crumb',
            field=models.IntegerField(default=50, help_text='0 for Dense, 100 for Open Crumb'),
        ),
        migrations.AddField(
            model_name='breadpreset',
            name='classifier_texture',
            field=models.IntegerField(default=50, help_text='0 for Crusty, 100 for Soft'),
        ),
        migrations.AddField(
            model_name='breadpreset',
            name='crumb_preview',
            field=models.CharField(default='Balanced', help_text='Crumb Structure Preview (Open, Balanced, or Even)', max_length=50),
        ),
        migrations.AddField(
            model_name='breadpreset',
            name='cultural_anchor',
            field=models.CharField(blank=True, help_text='Cultural anchor/history', max_length=250),
        ),
    ]
