# Generated by Django 6.0.4 on 2026-06-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_breadpreset_accessibility_definition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('equipment_type', models.CharField(choices=[('mill', 'Grain Mill'), ('mixer', 'Kneader / Mixer'), ('attachment', 'Mixer Attachment'), ('proofing_mat', 'Proofing Cabinet/Mat'), ('oven_accessory', 'Oven Accessory'), ('other', 'Other Equipment')], db_index=True, default='other', max_length=30)),
                ('friction_heat_factor', models.FloatField(default=0.0, help_text='Friction temperature rise in Fahrenheit (for mixers)')),
                ('ai_analyzed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Flexible specs generated by AI')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'indexes': [models.Index(fields=['equipment_type'], name='core_equipm_equipme_67d6fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='WheatBerry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('protein_content', models.FloatField(default=12.0, help_text='Protein percentage (e.g. 14.5 for 14.5%)')),
                ('hardness', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft'), ('durum', 'Durum'), ('ancient', 'Ancient')], default='hard', max_length=20)),
                ('moisture_absorption_coef', models.FloatField(default=1.0, help_text='Water absorption multiplier (e.g. 1.0 for baseline)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='True if currently in stock and included in calculations')),
                ('ai_analyzed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Wheat Berries',
                'indexes': [models.Index(fields=['is_active'], name='core_wheatb_is_acti_3aa4de_idx')],
            },
        ),
    ]
