# Generated by Django 6.0.4 on 2026-06-23 03:54

import uuid
from django.db import migrations, models


def convert_pk_to_uuid(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Check core_equipment
            cursor.execute("SELECT data_type FROM information_schema.columns WHERE table_name='core_equipment' AND column_name='id';")
            row = cursor.fetchone()
            if row and row[0] != 'uuid':
                cursor.execute('ALTER TABLE core_equipment ALTER COLUMN id DROP IDENTITY IF EXISTS;')
                cursor.execute('ALTER TABLE core_equipment ALTER COLUMN id TYPE uuid USING gen_random_uuid();')

            # Check core_wheatberry
            cursor.execute("SELECT data_type FROM information_schema.columns WHERE table_name='core_wheatberry' AND column_name='id';")
            row = cursor.fetchone()
            if row and row[0] != 'uuid':
                cursor.execute('ALTER TABLE core_wheatberry ALTER COLUMN id DROP IDENTITY IF EXISTS;')
                cursor.execute('ALTER TABLE core_wheatberry ALTER COLUMN id TYPE uuid USING gen_random_uuid();')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipment_wheatberry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('result', models.JSONField(blank=True, help_text='Success result payload', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wheatberry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(convert_pk_to_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wheatberry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
