# Generated by Django 6.0.4 on 2026-07-23 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backgroundtask_equipment_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'My Sourdough Boule'", max_length=200)),
                ('category_slug', models.CharField(max_length=100)),
                ('archetype_slug', models.CharField(max_length=100)),
                ('configuration_state', models.JSONField(help_text='The session state dictionary used to calculate this formula')),
                ('compiled_data', models.JSONField(help_text='The final output of calculate_final_recipe(state)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
