# Generated by Django 6.0.4 on 2026-08-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadpreset',
            name='sifting_requirement',
            field=models.CharField(choices=[('mandatory', 'Mandatory (High Extraction)'), ('optional', 'Optional (Variable)'), ('discouraged', 'Discouraged (Whole Grain)')], default='optional', help_text='Defines the structural baseline for bran separation.', max_length=20),
        ),
    ]
