# Generated by Django 5.0.14 on 2026-09-12 17:46

from django.db import migrations, utils, transaction

def rename_bake_to_cook(apps, schema_editor):
    try:
        with transaction.atomic():
            with schema_editor.connection.cursor() as cursor:
                cursor.execute('ALTER TABLE "core_formfactor" RENAME COLUMN "bake_temp_f" TO "cook_temp_f";')
    except (utils.ProgrammingError, utils.OperationalError):
        pass

def reverse_rename(apps, schema_editor):
    try:
        with transaction.atomic():
            with schema_editor.connection.cursor() as cursor:
                cursor.execute('ALTER TABLE "core_formfactor" RENAME COLUMN "cook_temp_f" TO "bake_temp_f";')
    except (utils.ProgrammingError, utils.OperationalError):
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_savedrecipe_category_slug_doughcategory_icon_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='formfactor',
                    old_name='bake_temp_f',
                    new_name='cook_temp_f',
                ),
            ],
            database_operations=[
                migrations.RunPython(rename_bake_to_cook, reverse_rename),
            ]
        )
    ]
