# Generated by Django 5.0.14 on 2026-09-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_savedrecipe_category_slug_doughcategory_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfactor',
            old_name='bake_temp_f',
            new_name='cook_temp_f',
        ),
    ]
