import uuid
from django.db import models
from .base import SoftDeleteModel

class WheatBerry(SoftDeleteModel):
    """
    Represents the wheat berries in the home baker's inventory.
    """
    class Hardness(models.TextChoices):
        HARD = 'hard', 'Hard'
        SOFT = 'soft', 'Soft'
        DURUM = 'durum', 'Durum'
        ANCIENT = 'ancient', 'Ancient'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, unique=True)
    protein_content = models.FloatField(default=12.0, help_text="Protein percentage (e.g. 14.5 for 14.5%)")
    hardness = models.CharField(max_length=20, choices=Hardness.choices, default=Hardness.HARD)
    moisture_absorption_coef = models.FloatField(default=1.0, help_text="Water absorption multiplier (e.g. 1.0 for baseline)")
    is_active = models.BooleanField(default=True, db_index=True, help_text="True if currently in stock and included in calculations")
    ai_analyzed = models.BooleanField(default=False)
    notes = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Wheat Berries"
        indexes = [
            models.Index(fields=['is_active']),
        ]

    def __str__(self):
        return f"{self.name} ({self.protein_content}%)"


class Equipment(SoftDeleteModel):
    """
    Represents baking equipment (mixers, mills, proofing tools, etc.).
    """
    class EquipmentType(models.TextChoices):
        MILL = 'mill', 'Grain Mill'
        MIXER = 'mixer', 'Kneader / Mixer'
        ATTACHMENT = 'attachment', 'Mixer Attachment'
        PROOFING_MAT = 'proofing_mat', 'Proofing Cabinet/Mat'
        OVEN_ACCESSORY = 'oven_accessory', 'Oven Accessory'
        OTHER = 'other', 'Other Equipment'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, unique=True)
    equipment_type = models.CharField(max_length=30, choices=EquipmentType.choices, default=EquipmentType.OTHER, db_index=True)
    friction_heat_factor = models.FloatField(default=0.0, help_text="Friction temperature rise in Fahrenheit (for mixers)")
    ai_analyzed = models.BooleanField(default=False)
    notes = models.TextField(blank=True)
    details = models.JSONField(default=dict, blank=True, help_text="Flexible specs generated by AI")

    class Meta:
        verbose_name_plural = "Equipment"
        indexes = [
            models.Index(fields=['equipment_type']),
        ]

    def __str__(self):
        return f"{self.name} ({self.get_equipment_type_display()})"
